# Generated by Django 2.2 on 2022-03-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='codigo',
            field=models.CharField(default='123456am', max_length=8),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
